version: '3'

volumes:
    mongo_data:

services:
    #ganache:
    #  restart: always
    #  build: ./ganache
    #  image: ganache:ganache
    #  command: docker run -d -p "7545:7545" --net=host -e DISPLAY=:0 --name  ganache ganache 
    #  ports:
    #    - "7545:7545"


    chainvote-api:
      restart: always
      stdin_open: true
      tty: true
      build: .
      command: uvicorn main:app --host 0.0.0.0 --port 8085 --debug --reload 
      volumes:
        - ./chainvote-api:/chainvote-api
      ports:
        - "5555:8085"
      depends_on:
        - chainvote-db
        - chainvote-cache
        #- ganache


    chainvote-cache:
      restart: always
      image: "redis:alpine"
      command: --port 6380
      ports:
        - "6380:6380"
      expose:
        - "6380"
    
    chainvote-db:
      restart: always
      image: mongo
      command: mongod --port 27018
      environment:
        MONGO_INITDB_ROOT_USERNAME: "chainvote_user_db"
        MONGO_INITDB_ROOT_PASSWORD: ":-?<!k29qs^QrM?p"
      volumes:
        - mongo_data:/data/db
      ports:
        - "27018:27018"
